language: fa

pipeline:
- name: HFTransformersNLP
  model_name: "HooshvareLab/distilbert-fa-zwnj-base"
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: DIETClassifier
  epochs: 100
  transformer_size: 256
  number_of_transformer_layers: 2
  number_of_attention_heads: 4
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 50

policies:
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 100
  transformer_size: 256
- name: RulePolicy